name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      env:
        CGO_ENABLED: '0'
      run: go build -v
    - name: Test
      shell: bash
      env:
        PASSWORD: password
        PLAINTEXT: The secret message
        ENCRYPTED: |
          AQgAAAAAABAABFkVTScVNMr2euF8TzNIyBSi8KfktCPlkskkRPzhVPA2ZAygHpLBt474YbWJARBs
          SCiNiIaQEflH3fALH7Cm4pWTgi43aP3QJL2Q
      run: |
        echo -n "${PLAINTEXT}" > plaintext
        echo -n "${ENCRYPTED}" | base64 -d > encrypted
        ./goenc -d encrypted decrypted
        cmp plaintext decrypted

        openssl rand -out plaintext2 2048
        ./goenc plaintext2 encrypted2
        ./goenc -d encrypted2 decrypted2
        cmp plaintext2 decrypted2

  create-release:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create --draft "${GITHUB_REF#refs/tags/}"

  upload-release:
    runs-on: ubuntu-latest
    needs: [create-release]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        GOOS: [windows, darwin, linux]
        GOARCH: [amd64]
        include:
        - GOOS: android
          GOARCH: arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Build release assets
      env:
        CGO_ENABLED: '0'
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        GOHOSTOS: linux
        GOHOSTARCH: amd64
      run: |
        go install -trimpath -ldflags "-s -w" "github.com/${GITHUB_REPOSITORY}@${GITHUB_REF#refs/tags/}"

        ARTIFACT_DIR="goenc-${GOOS}-${GOARCH}-${GITHUB_REF#refs/tags/v}"
        mkdir "${ARTIFACT_DIR}"
        cp LICENSE README.md "${ARTIFACT_DIR}"

        if [[ "${GOOS}/${GOARCH}" == "${GOHOSTOS}/${GOHOSTARCH}" ]]; then
          GOBIN="$(go env GOPATH)/bin"
        else
          GOBIN="$(go env GOPATH)/bin/${GOOS}_${GOARCH}"
        fi
        GOEXE="$(go env GOEXE)"
        cp "${GOBIN}/goenc${GOEXE}" "${ARTIFACT_DIR}"
    - name: Upload release assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
      run: |
        ARTIFACT_DIR="goenc-${GOOS}-${GOARCH}-${GITHUB_REF#refs/tags/v}"
        if [[ "${GOOS}" == "windows" ]]; then
          zip "${ARTIFACT_DIR}.zip" "${ARTIFACT_DIR}"/*
          gh release upload "${GITHUB_REF#refs/tags/}" "${ARTIFACT_DIR}.zip"
        else
          tar zcf "${ARTIFACT_DIR}.tar.gz" "${ARTIFACT_DIR}"
          gh release upload "${GITHUB_REF#refs/tags/}" "${ARTIFACT_DIR}.tar.gz"
        fi
